"""Graph B: Deployment scaffolder.

Edges:
  parse_request → research_service → assess_helm → load_conventions
  → (route_helm) → generate_helmrelease / generate_kustomize
  → self_review → (route_review) → commit_and_pr / retry generate node
  → END

The self_review retry loop runs up to MAX_RETRIES=2 times before
falling through to commit_and_pr regardless of review outcome.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any, Literal

import git as gitlib
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, StateGraph
from langgraph.prebuilt import create_react_agent
from pydantic import BaseModel

from ops_agent.config import get_settings
from ops_agent.llm.personas import get_llm
from ops_agent.state import DeployScaffoldState, EvidenceItem
from ops_agent.tools.fetch import get_fetch_tool
from ops_agent.tools.gitea import GiteaClient
from ops_agent.tools.search import get_search_tool

MAX_RETRIES = 2

# ---------------------------------------------------------------------------
# Pydantic schemas for structured LLM output
# ---------------------------------------------------------------------------


class ServiceSpec(BaseModel):
    """Parsed deployment specification from user request."""

    name: str
    image: str | None = None
    namespace: str = "default"
    ports: list[int] = []
    env: dict[str, str] = {}
    volumes: list[str] = []
    provided_links: list[str] = []


class ReviewResult(BaseModel):
    """Outcome of the self-review step."""

    passed: bool
    issues: list[str]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _format_evidence(evidence: list[EvidenceItem]) -> str:
    if not evidence:
        return "(no evidence gathered)"
    return "\n\n---\n\n".join(
        f"[{e.source}] {e.url or ''}\n{e.text[:1000]}" for e in evidence
    )


def _extract_manifests(llm_output: str) -> dict[str, str]:
    """Parse a JSON object mapping filename→YAML content from LLM output."""
    try:
        json_match = re.search(r"\{.*\}", llm_output, re.DOTALL)
        if json_match:
            data = json.loads(json_match.group(0))
            if isinstance(data, dict) and all(isinstance(v, str) for v in data.values()):
                return data
    except Exception:
        pass
    return {"output.yaml": llm_output}


def _build_pr_body(state: DeployScaffoldState) -> str:
    spec = state.get("spec", {})
    manifests = state.get("manifests", {})
    helm_ref = state.get("helm_chart_ref")
    issue_number = state.get("issue_number")

    lines = [
        "## Deployment Scaffold",
        "",
        f"**Service:** `{spec.get('name', 'unknown')}`",
        f"**Namespace:** `{spec.get('namespace', 'default')}`",
        f"**Helm chart:** {'`' + helm_ref + '`' if helm_ref else 'N/A (Kustomize)'}",
        "",
        "### Generated files",
    ]
    for fname in manifests:
        lines.append(f"- `apps/{spec.get('name', 'service')}/{fname}`")
    lines += ["", "---", "*Generated by ops-agent*"]

    if issue_number:
        lines.append(f"\nCloses #{issue_number}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Node 1: parse_request
# ---------------------------------------------------------------------------

_PARSE_SYSTEM = """\
You are a deployment spec parser. Given a user request describing a service to
deploy, extract a structured specification and any URLs the user provided.

Return a ServiceSpec with:
- name: service name (lowercase, hyphen-separated, no spaces)
- image: docker image reference if explicitly mentioned, else null
- namespace: kubernetes namespace (default: "default")
- ports: list of integer port numbers the service exposes
- env: dict of environment variable names to values or descriptions
- volumes: list of volume mount paths or descriptions
- provided_links: list of any URLs mentioned in the request
"""


def parse_request(state: DeployScaffoldState) -> dict[str, Any]:
    """Parse the user request into a structured spec dict and extract links.

    On failure, logs error and returns empty spec to allow downstream nodes to proceed.
    """
    try:
        llm = get_llm("instruct")
        structured_llm = llm.with_structured_output(ServiceSpec)

        messages = [
            SystemMessage(content=_PARSE_SYSTEM),
            HumanMessage(content=f"User request:\n{state['request']}"),
        ]

        result: ServiceSpec = structured_llm.invoke(messages)  # type: ignore[assignment]
        return {
            "spec": result.model_dump(exclude={"provided_links"}),
            "provided_links": result.provided_links,
        }
    except Exception as exc:
        import sys
        print(f"Warning: parse_request failed: {exc}", file=sys.stderr)
        return {
            "spec": {"name": "unknown", "namespace": "default", "ports": [], "env": {}, "volumes": []},
            "provided_links": [],
        }


# ---------------------------------------------------------------------------
# Node 2: research_service
# ---------------------------------------------------------------------------

_RESEARCH_SERVICE_SYSTEM = """\
You are a deployment researcher. Given a service name and any links provided by
the user, find the Docker image, exposed ports, required environment variables,
volumes, and any compose/install documentation.

Use web_search and fetch_url to:
1. Follow provided links to find installation docs, docker-compose examples, etc.
2. Locate the official container image on Docker Hub or the project's registry.
3. Find any example docker-compose.yml or Kubernetes deployment documentation.

Return a JSON list of objects with keys: source, url, text.
Do NOT speculate — only report what you actually retrieved.
"""


def research_service(state: DeployScaffoldState) -> dict[str, Any]:
    """Tool-calling agent that gathers service deployment evidence.

    On failure, logs error and returns empty evidence to allow downstream nodes to proceed.
    """
    try:
        spec = state.get("spec", {})
        name = spec.get("name", state["request"][:60])
        links = state.get("provided_links", [])

        llm = get_llm("research")
        tools = [get_search_tool(), get_fetch_tool()]
        agent = create_react_agent(llm, tools, prompt=_RESEARCH_SERVICE_SYSTEM)

        link_block = "\n".join(f"- {url}" for url in links) if links else "(none provided)"
        user_msg = (
            f"Service to deploy: {name}\n"
            f"Provided links:\n{link_block}\n\n"
            "Find: docker image name, exposed ports, required env vars, volumes, "
            "and docker-compose or install documentation. "
            "Return a JSON list of objects with keys: source, url, text."
        )

        result = agent.invoke({"messages": [HumanMessage(content=user_msg)]})
        output: str = result["messages"][-1].content

        evidence: list[EvidenceItem] = []
        try:
            json_match = re.search(r"\[.*\]", output, re.DOTALL)
            if json_match:
                items = json.loads(json_match.group(0))
                for item in items:
                    if isinstance(item, dict) and "text" in item:
                        evidence.append(
                            EvidenceItem(
                                source=item.get("source", "web"),
                                url=item.get("url"),
                                text=str(item["text"]),
                            )
                        )
        except Exception:
            if output.strip():
                evidence.append(EvidenceItem(source="agent_output", url=None, text=output[:4000]))

        return {"service_evidence": evidence}
    except Exception as exc:
        import sys
        print(f"Warning: research_service failed: {exc}", file=sys.stderr)
        return {"service_evidence": []}


# ---------------------------------------------------------------------------
# Node 3: assess_helm
# ---------------------------------------------------------------------------

_ASSESS_HELM_SYSTEM = """\
You are a Helm chart assessor. Determine whether a well-maintained upstream Helm
chart exists for the given service.

Use web_search and fetch_url to:
1. Search Artifact Hub (artifacthub.io) for the service name.
2. Check the project's own repository for a charts/ directory.
3. Check Bitnami, bjw-s, or other well-known chart repositories.

Return a JSON object:
{
  "helm_chart_found": true or false,
  "helm_chart_ref": "chart reference string or null",
  "source_url": "url where found or null",
  "evidence": [{"source": "...", "url": "...", "text": "..."}]
}
"""


def assess_helm(state: DeployScaffoldState) -> dict[str, Any]:
    """Tool-calling agent that determines whether an upstream Helm chart exists.

    On failure, logs error and assumes no Helm chart to allow downstream nodes to proceed.
    """
    try:
        spec = state.get("spec", {})
        name = spec.get("name", state["request"][:60])

        llm = get_llm("research")
        tools = [get_search_tool(), get_fetch_tool()]
        agent = create_react_agent(llm, tools, prompt=_ASSESS_HELM_SYSTEM)

        user_msg = (
            f"Assess whether a well-maintained upstream Helm chart exists for: {name}\n"
            "Return the JSON object described in your instructions."
        )

        result = agent.invoke({"messages": [HumanMessage(content=user_msg)]})
        output: str = result["messages"][-1].content

        helm_found = False
        helm_ref: str | None = None
        extra_evidence: list[EvidenceItem] = []

        try:
            json_match = re.search(r"\{.*\}", output, re.DOTALL)
            if json_match:
                data = json.loads(json_match.group(0))
                helm_found = bool(data.get("helm_chart_found", False))
                helm_ref = data.get("helm_chart_ref") or None
                for item in data.get("evidence", []):
                    if isinstance(item, dict) and "text" in item:
                        extra_evidence.append(
                            EvidenceItem(
                                source=item.get("source", "helm-research"),
                                url=item.get("url"),
                                text=str(item["text"]),
                            )
                        )
        except Exception:
            if output.strip():
                extra_evidence.append(
                    EvidenceItem(source="helm_research_output", url=None, text=output[:2000])
                )

        return {
            "helm_chart_found": helm_found,
            "helm_chart_ref": helm_ref,
            "service_evidence": extra_evidence,
        }
    except Exception as exc:
        import sys
        print(f"Warning: assess_helm failed: {exc}", file=sys.stderr)
        return {
            "helm_chart_found": False,
            "helm_chart_ref": None,
            "service_evidence": [],
        }


# ---------------------------------------------------------------------------
# Node 4: load_conventions
# ---------------------------------------------------------------------------

_CONVENTIONS_SYSTEM = """\
You are a Kubernetes/GitOps conventions analyst. Given the contents of a homelab
Flux/Kustomize repository, summarize the conventions used so a code generator can
follow them. Focus on:
- Directory structure (apps/, infrastructure/, etc.)
- Namespace conventions
- Common labels and annotations
- HelmRelease structure if Flux is used
- Kustomization file patterns
- Naming patterns for secrets, configmaps, etc.

Be concise — this summary will be passed to a code generator.
"""


def load_conventions(state: DeployScaffoldState) -> dict[str, Any]:
    """Read the example repo and summarize its layout conventions."""
    settings = get_settings()
    repo_path = settings.example_repo_path

    if not repo_path:
        return {"conventions": "No example repo configured. Use generic Kubernetes/Flux conventions."}

    repo_dir = Path(repo_path)
    if not repo_dir.exists():
        return {"conventions": f"Example repo not found at {repo_path}. Using generic conventions."}

    structure_lines: list[str] = []
    sample_files: dict[str, str] = {}

    for root, dirs, files in os.walk(repo_dir):
        dirs[:] = [d for d in dirs if not d.startswith(".") and d not in ("node_modules",)]
        rel_root = Path(root).relative_to(repo_dir)
        depth = len(rel_root.parts)
        if depth > 3:
            continue
        indent = "  " * depth
        structure_lines.append(f"{indent}{rel_root}/")
        for fname in files:
            fpath = Path(root) / fname
            structure_lines.append(f"{indent}  {fname}")
            if fname.endswith((".yaml", ".yml")) and len(sample_files) < 6:
                try:
                    content = fpath.read_text(encoding="utf-8")
                    sample_files[str(fpath.relative_to(repo_dir))] = content[:1500]
                except Exception:
                    pass

    structure = "\n".join(structure_lines[:120])
    samples_block = "\n\n".join(
        f"### {path}\n```yaml\n{content}\n```"
        for path, content in sample_files.items()
    )

    llm = get_llm("research")
    messages = [
        SystemMessage(content=_CONVENTIONS_SYSTEM),
        HumanMessage(
            content=(
                f"Repository structure:\n{structure}\n\n"
                f"Sample files:\n{samples_block}\n\n"
                "Summarize the conventions."
            )
        ),
    ]

    response = llm.invoke(messages)
    conventions: str = response.content if hasattr(response, "content") else str(response)
    return {"conventions": conventions}


# ---------------------------------------------------------------------------
# Node 5a: generate_helmrelease
# ---------------------------------------------------------------------------

_HELMRELEASE_SYSTEM = """\
You are a Flux HelmRelease generator. Generate Kubernetes manifests to deploy a
service using a Flux HelmRelease and a values.yaml override file.

Follow the conventions provided. Use the service evidence for image tag, ports,
env variables, and volume details. Return ONLY valid YAML — no prose.

Output a JSON object mapping filename → file content:
{
  "helmrelease.yaml": "...",
  "values.yaml": "..."
}
"""


def generate_helmrelease(state: DeployScaffoldState) -> dict[str, Any]:
    """Generate Flux HelmRelease + values.yaml manifests."""
    spec = state.get("spec", {})
    review_issues = state.get("review_issues", [])
    issue_block = "\n".join(f"- {i}" for i in review_issues) if review_issues else ""

    llm = get_llm("coding")
    messages = [
        SystemMessage(content=_HELMRELEASE_SYSTEM),
        HumanMessage(
            content=(
                f"Service spec: {json.dumps(spec, indent=2)}\n\n"
                f"Helm chart: {state.get('helm_chart_ref') or 'unknown'}\n\n"
                f"Conventions:\n{state.get('conventions', '')}\n\n"
                f"Service evidence:\n{_format_evidence(state.get('service_evidence', []))}\n\n"
                + (f"Previous review issues (fix these):\n{issue_block}\n\n" if issue_block else "")
                + "Generate the HelmRelease and values.yaml."
            )
        ),
    ]

    response = llm.invoke(messages)
    content: str = response.content if hasattr(response, "content") else str(response)
    manifests = _extract_manifests(content)

    retry_increment = 1 if review_issues else 0
    return {
        "manifests": manifests,
        "retry_count": state.get("retry_count", 0) + retry_increment,
        "review_issues": [],
    }


# ---------------------------------------------------------------------------
# Node 5b: generate_kustomize
# ---------------------------------------------------------------------------

_KUSTOMIZE_SYSTEM = """\
You are a Kustomize manifest generator. Generate Kubernetes manifests to deploy a
service using plain Kustomize (no Helm). Include a Deployment, Service, and
kustomization.yaml.

Follow the conventions provided. Use the service evidence for image, ports, env
variables, and volume details. Return ONLY valid YAML — no prose.

Output a JSON object mapping filename → file content:
{
  "deployment.yaml": "...",
  "service.yaml": "...",
  "kustomization.yaml": "..."
}
"""


def generate_kustomize(state: DeployScaffoldState) -> dict[str, Any]:
    """Generate Kustomize Deployment/Service manifests."""
    spec = state.get("spec", {})
    review_issues = state.get("review_issues", [])
    issue_block = "\n".join(f"- {i}" for i in review_issues) if review_issues else ""

    llm = get_llm("coding")
    messages = [
        SystemMessage(content=_KUSTOMIZE_SYSTEM),
        HumanMessage(
            content=(
                f"Service spec: {json.dumps(spec, indent=2)}\n\n"
                f"Conventions:\n{state.get('conventions', '')}\n\n"
                f"Service evidence:\n{_format_evidence(state.get('service_evidence', []))}\n\n"
                + (f"Previous review issues (fix these):\n{issue_block}\n\n" if issue_block else "")
                + "Generate the Deployment, Service, and kustomization.yaml."
            )
        ),
    ]

    response = llm.invoke(messages)
    content: str = response.content if hasattr(response, "content") else str(response)
    manifests = _extract_manifests(content)

    retry_increment = 1 if review_issues else 0
    return {
        "manifests": manifests,
        "retry_count": state.get("retry_count", 0) + retry_increment,
        "review_issues": [],
    }


# ---------------------------------------------------------------------------
# Node 6: self_review
# ---------------------------------------------------------------------------

_SELF_REVIEW_SYSTEM = """\
You are a Kubernetes manifest reviewer. Check the generated manifests against
the provided conventions and this checklist:

- All required fields are present (apiVersion, kind, metadata.name, etc.)
- Namespace is set and matches the spec
- Container image reference is not a placeholder ("unknown", "TODO", etc.)
- Port numbers in the Service selector match those in the Deployment
- Labels and selectors are consistent between Deployment and Service
- No raw secret values in env (use secretKeyRef or separate Secret objects)
- Follows the repository conventions

Return ONLY a JSON object: {"passed": true/false, "issues": ["issue 1", ...]}
If there are no issues, return {"passed": true, "issues": []}
"""


def self_review(state: DeployScaffoldState) -> dict[str, Any]:
    """Check generated manifests against conventions; structured output."""
    manifests = state.get("manifests", {})
    if not manifests:
        return {"review_passed": False, "review_issues": ["No manifests were generated."]}

    manifest_block = "\n\n".join(
        f"### {fname}\n```yaml\n{content}\n```" for fname, content in manifests.items()
    )

    llm = get_llm("extract")
    structured_llm = llm.with_structured_output(ReviewResult)

    messages = [
        SystemMessage(content=_SELF_REVIEW_SYSTEM),
        HumanMessage(
            content=(
                f"Service spec: {json.dumps(state.get('spec', {}), indent=2)}\n\n"
                f"Conventions:\n{state.get('conventions', '')}\n\n"
                f"Generated manifests:\n{manifest_block}"
            )
        ),
    ]

    result: ReviewResult = structured_llm.invoke(messages)  # type: ignore[assignment]
    return {"review_passed": result.passed, "review_issues": result.issues}


# ---------------------------------------------------------------------------
# Node 7: commit_and_pr
# ---------------------------------------------------------------------------


def commit_and_pr(state: DeployScaffoldState) -> dict[str, Any]:
    """Write manifests to the repo working tree, commit, push, open a Gitea PR."""
    settings = get_settings()
    repo_path = settings.example_repo_path
    if not repo_path:
        return {"pr_url": "ERROR: example_repo_path not configured; cannot commit."}

    spec = state.get("spec", {})
    service_name = spec.get("name", "service")
    branch = f"ops-agent/deploy-{service_name}"
    manifests = state.get("manifests", {})

    deploy_dir = Path(repo_path) / "apps" / service_name
    deploy_dir.mkdir(parents=True, exist_ok=True)
    for fname, content in manifests.items():
        (deploy_dir / fname).write_text(content, encoding="utf-8")

    try:
        repo = gitlib.Repo(repo_path)
        new_branch = repo.create_head(branch)
        new_branch.checkout()
        repo.git.add(A=True)
        author = gitlib.Actor(settings.git_author_name, settings.git_author_email)
        issue_number = state.get("issue_number")
        commit_msg = f"feat: add {service_name} deployment manifests"
        if issue_number:
            commit_msg += f" #{issue_number}"
        repo.index.commit(
            commit_msg,
            author=author,
            committer=author,
        )
        repo.remotes.origin.push(refspec=f"{branch}:{branch}")
    except Exception as exc:
        return {"pr_url": f"Git error: {exc}"}

    owner: str = state.get("_owner", "")  # type: ignore[typeddict-item]
    repo_name: str = state.get("_repo", "")  # type: ignore[typeddict-item]

    if not owner or not repo_name:
        return {"pr_url": f"Branch '{branch}' pushed. Set _owner/_repo in state to auto-open PR."}

    try:
        client = GiteaClient()
        try:
            pr = client.create_pr(
                owner=owner,
                repo=repo_name,
                title=f"feat: deploy {service_name}",
                body=_build_pr_body(state),
                head=branch,
                base="main",
            )
            pr_url = pr.get("html_url", str(pr))
        finally:
            client.close()
    except Exception as exc:
        pr_url = f"Branch pushed but PR creation failed: {exc}"

    return {"pr_url": pr_url}


# ---------------------------------------------------------------------------
# Routing functions
# ---------------------------------------------------------------------------


def _route_after_conventions(
    state: DeployScaffoldState,
) -> Literal["generate_helmrelease", "generate_kustomize"]:
    """Route to Helm or Kustomize generator based on helm_chart_found."""
    return "generate_helmrelease" if state.get("helm_chart_found") else "generate_kustomize"


def _route_after_review(
    state: DeployScaffoldState,
) -> Literal["generate_helmrelease", "generate_kustomize", "commit_and_pr"]:
    """Retry the generate node if review failed and retries remain; else commit."""
    passed = state.get("review_passed", False)
    retries = state.get("retry_count", 0)

    if not passed and retries < MAX_RETRIES:
        return "generate_helmrelease" if state.get("helm_chart_found") else "generate_kustomize"
    return "commit_and_pr"


# ---------------------------------------------------------------------------
# Graph assembly
# ---------------------------------------------------------------------------


def build_scaffold_graph() -> Any:
    """Build and compile the deployment scaffolder graph.

    Topology:
      parse_request → research_service → assess_helm → load_conventions
      → (helm?) → generate_helmrelease / generate_kustomize
      → self_review → (passed? retries?) → commit_and_pr / retry generate
      → END

    Compiled with checkpointing support if PostgreSQL is available.
    """
    from ops_agent.checkpointing import get_checkpoint_saver

    graph = StateGraph(DeployScaffoldState)

    graph.add_node("parse_request", parse_request)
    graph.add_node("research_service", research_service)
    graph.add_node("assess_helm", assess_helm)
    graph.add_node("load_conventions", load_conventions)
    graph.add_node("generate_helmrelease", generate_helmrelease)
    graph.add_node("generate_kustomize", generate_kustomize)
    graph.add_node("self_review", self_review)
    graph.add_node("commit_and_pr", commit_and_pr)

    graph.set_entry_point("parse_request")
    graph.add_edge("parse_request", "research_service")
    graph.add_edge("research_service", "assess_helm")
    graph.add_edge("assess_helm", "load_conventions")

    graph.add_conditional_edges(
        "load_conventions",
        _route_after_conventions,
        {
            "generate_helmrelease": "generate_helmrelease",
            "generate_kustomize": "generate_kustomize",
        },
    )

    graph.add_edge("generate_helmrelease", "self_review")
    graph.add_edge("generate_kustomize", "self_review")

    graph.add_conditional_edges(
        "self_review",
        _route_after_review,
        {
            "generate_helmrelease": "generate_helmrelease",
            "generate_kustomize": "generate_kustomize",
            "commit_and_pr": "commit_and_pr",
        },
    )

    graph.add_edge("commit_and_pr", END)

    checkpointer = get_checkpoint_saver()
    if checkpointer:
        return graph.compile(checkpointer=checkpointer)
    return graph.compile()


# ---------------------------------------------------------------------------
# Public run helper
# ---------------------------------------------------------------------------


def run(
    prompt: str,
    owner: str = "",
    repo: str = "",
    issue_number: int | None = None,
    id: str | None = None,
    thread_id: str | None = None,
) -> str | None:
    """Run the full scaffold graph for a deployment request.

    If thread_id is provided, the graph will resume from checkpoint if it exists.
    Otherwise, a fresh run is performed.

    Args:
        prompt: Deployment request text
        owner: Optional Gitea repo owner
        repo: Optional Gitea repo name
        issue_number: Optional issue number to link
        id: Optional explicit checkpoint ID (required if using prompt/prompt_file without issue)
        thread_id: Optional explicit thread ID for checkpointing

    Returns the PR URL from the final state, or None if not set.
    """
    compiled = build_scaffold_graph()

    # Determine the checkpoint thread_id
    if thread_id:
        checkpoint_id = thread_id
    elif issue_number:
        checkpoint_id = f"issue_{issue_number}"
    elif id:
        checkpoint_id = id
    else:
        checkpoint_id = "scaffold_deploy_no_id"

    initial_state: dict[str, Any] = {
        "request": prompt,
        "thread_id": checkpoint_id,
        "provided_links": [],
        "spec": {},
        "service_evidence": [],
        "helm_chart_found": False,
        "helm_chart_ref": None,
        "conventions": "",
        "manifests": {},
        "review_passed": False,
        "review_issues": [],
        "retry_count": 0,
        "pr_url": None,
        "_owner": owner,
        "_repo": repo,
        "issue_number": issue_number,
    }

    # Use thread_id for checkpoint resumption if available
    if checkpoint_id and checkpoint_id != "scaffold_deploy_no_id":
        final_state = compiled.invoke(initial_state, config={"configurable": {"thread_id": checkpoint_id}})
    else:
        final_state = compiled.invoke(initial_state)
    return final_state.get("pr_url")
