"""Node: commit_and_pr - writes manifests, commits, pushes, opens PR."""

from pathlib import Path
from typing import Any

import git as gitlib

from ops_agent.config import get_settings
from ops_agent.state import ServiceDeployState
from ops_agent.tools.gitea import GiteaClient
from ops_agent.types import EvidenceItem


def _format_evidence(evidence: list[EvidenceItem]) -> str:
    if not evidence:
        return "(no evidence gathered)"
    return "\n\n---\n\n".join(
        f"[{e.source}] {e.url or ''}\n{e.text[:1000]}" for e in evidence
    )


def _build_pr_body(state: ServiceDeployState) -> str:
    spec = state.get("spec", {})
    manifests = state.get("manifests", {})
    helm_ref = state.get("helm_chart_ref")
    issue_number = state.get("issue_number")

    lines = [
        "## Deployment Scaffold",
        "",
        f"**Service:** `{spec.get('name', 'unknown')}`",
        f"**Namespace:** `{spec.get('namespace', 'default')}`",
        f"**Helm chart:** {'`' + helm_ref + '`' if helm_ref else 'N/A (Kustomize)'}",
        "",
        "### Generated files",
    ]
    for fname in manifests:
        lines.append(f"- `apps/{spec.get('name', 'service')}/{fname}`")
    lines += ["", "---", "*Generated by ops-agent*"]

    if issue_number:
        lines.append(f"\nCloses #{issue_number}")

    return "\n".join(lines)


def commit_and_pr(state: ServiceDeployState) -> dict[str, Any]:
    """Write manifests to the repo working tree, commit, push, open a Gitea PR."""
    settings = get_settings()
    repo_path = settings.example_repo_path
    if not repo_path:
        return {"pr_url": "ERROR: example_repo_path not configured; cannot commit."}

    spec = state.get("spec", {})
    service_name = spec.get("name", "service")
    branch = f"ops-agent/deploy-{service_name}"
    manifests = state.get("manifests", {})

    deploy_dir = Path(repo_path) / "apps" / service_name
    deploy_dir.mkdir(parents=True, exist_ok=True)
    for fname, content in manifests.items():
        (deploy_dir / fname).write_text(content, encoding="utf-8")

    try:
        repo = gitlib.Repo(repo_path)
        new_branch = repo.create_head(branch)
        new_branch.checkout()
        repo.git.add(A=True)
        author = gitlib.Actor(settings.git_author_name, settings.git_author_email)
        issue_number = state.get("issue_number")
        commit_msg = f"feat: add {service_name} deployment manifests"
        if issue_number:
            commit_msg += f" #{issue_number}"
        repo.index.commit(
            commit_msg,
            author=author,
            committer=author,
        )
        repo.remotes.origin.push(refspec=f"{branch}:{branch}")
    except Exception as exc:
        return {"pr_url": f"Git error: {exc}"}

    owner: str = state.get("_owner", "")  # type: ignore[typeddict-item]
    repo_name: str = state.get("_repo", "")  # type: ignore[typeddict-item]

    if not owner or not repo_name:
        return {"pr_url": f"Branch '{branch}' pushed. Set _owner/_repo in state to auto-open PR."}

    try:
        client = GiteaClient()
        try:
            pr = client.create_pr(
                owner=owner,
                repo=repo_name,
                title=f"feat: deploy {service_name}",
                body=_build_pr_body(state),
                head=branch,
                base="main",
            )
            pr_url = pr.get("html_url", str(pr))
        finally:
            client.close()
    except Exception as exc:
        pr_url = f"Branch pushed but PR creation failed: {exc}"

    return {"pr_url": pr_url}
