"""Node: commit_and_pr - clones/syncs repo, writes manifests, commits, pushes, opens PR."""

import base64
import logging
import shlex
from pathlib import Path
from typing import Any

import git as gitlib

from ops_agent.config import get_settings
from ops_agent.state import ServiceDeployState
from ops_agent.tools.github import GitHubClient
from ops_agent.types import EvidenceItem

logger = logging.getLogger(__name__)

# Push result flags that mean the remote refused the update. A silent
# non-fast-forward rejection would otherwise let us post an acknowledgment
# claiming a push that never landed.
_PUSH_ERROR_FLAGS = (
    gitlib.PushInfo.ERROR
    | gitlib.PushInfo.REJECTED
    | gitlib.PushInfo.REMOTE_REJECTED
    | gitlib.PushInfo.REMOTE_FAILURE
)


def _auth_header_value(token: str) -> str:
    """Build the git HTTP auth header value for GitHub.

    GitHub's git-over-HTTPS wants Basic auth with the literal username
    ``x-access-token`` — unlike Gitea, which accepted ``Authorization: token <T>``.
    """
    encoded = base64.b64encode(f"x-access-token:{token}".encode()).decode()
    return f"Authorization: Basic {encoded}"


def _format_evidence(evidence: list[EvidenceItem]) -> str:
    if not evidence:
        return "(no evidence gathered)"
    return "\n\n---\n\n".join(
        f"[{e.source}] {e.url or ''}\n{e.text[:1000]}" for e in evidence
    )


def _build_pr_body(state: ServiceDeployState) -> str:
    spec = state.get("spec", {})
    manifests = state.get("manifests", {})
    helm_ref = state.get("helm_chart_ref")
    issue_number = state.get("issue_number")

    lines = [
        "## Deployment Scaffold",
        "",
        f"**Service:** `{spec.get('name', 'unknown')}`",
        f"**Namespace:** `{spec.get('namespace', 'default')}`",
        f"**Helm chart:** {'`' + helm_ref + '`' if helm_ref else 'N/A (Kustomize)'}",
        "",
        "### Generated files",
    ]
    for fname in manifests:
        lines.append(f"- `apps/{spec.get('name', 'service')}/{fname}`")
    lines += ["", "---", "*Generated by ops-agent*"]

    if issue_number:
        lines.append(f"\nCloses #{issue_number}")

    return "\n".join(lines)


def _build_steer_ack(state: ServiceDeployState) -> str:
    """Short comment acknowledging the steering request we just applied."""
    new_inputs = state.get("new_inputs", []) or []
    quoted = "\n".join(f"> @{c.get('author', '?')}: {c.get('text', '')}" for c in new_inputs)
    files = ", ".join(f"`{f}`" for f in state.get("manifests", {})) or "(none)"
    return (
        "## 🔧 Updated deployment per your comment\n\n"
        f"{quoted}\n\n"
        f"Regenerated and pushed: {files}\n\n"
        "---\n*Updated by ops-agent*"
    )


def _set_auth_header(repo: gitlib.Repo, token: str) -> None:
    """Persist the GitHub token auth header in the repo config.

    This makes token auth work for all HTTPS operations (fetch/pull/push),
    not just the initial clone.
    """
    with repo.config_writer() as cw:
        cw.set_value("http", "extraHeader", _auth_header_value(token))


def _get_or_clone_repo(
    owner: str,
    repo_name: str,
    workdir: Path,
    github_url: str,
    token: str,
) -> Path:
    """Ensure repo is cloned to workdir/owner/repo_name, clone if missing.

    Uses token-based HTTPS auth. Returns the repo path.
    """
    repo_dir = workdir / owner / repo_name

    if repo_dir.exists() and (repo_dir / ".git").exists():
        logger.info("Repo already exists at %s", repo_dir)
        _set_auth_header(gitlib.Repo(repo_dir), token)
        return repo_dir

    repo_dir.parent.mkdir(parents=True, exist_ok=True)
    github_url_clean = github_url.rstrip("/")
    clone_url = f"{github_url_clean}/{owner}/{repo_name}.git"

    logger.info("Cloning %s to %s", clone_url, repo_dir)
    # GitPython whitespace-splits each multi_options entry via
    # ``shlex.split(" ".join(multi_options))``, so the space in the header
    # value must be quoted or "-c http.extraHeader=Authorization: token <T>"
    # is parsed as multiple args ("fatal: Too many arguments").
    # The token is now base64-encoded in .git/config (no worse than before,
    # but not obfuscation).
    header = f"http.extraHeader={_auth_header_value(token)}"
    repo = gitlib.Repo.clone_from(
        clone_url,
        str(repo_dir),
        multi_options=["-c", shlex.quote(header)],
        allow_unsafe_options=True,
    )
    # Persist the header so later pull/push also authenticate.
    _set_auth_header(repo, token)
    return repo_dir


def _remote_branch_exists(repo: gitlib.Repo, branch_name: str) -> bool:
    """True if origin already has this branch (an open PR branch to update)."""
    return branch_name in [ref.remote_head for ref in repo.remotes.origin.refs]


def _sync_and_branch(repo_dir: Path, branch_name: str) -> None:
    """Prepare a correct local base for ``branch_name``, then check it out.

    Fetches first, then chooses the base so the follow-up commit always
    fast-forwards on push and never diverges from existing history — even on a
    fresh clone where the local branch is absent:

      * if origin already has the branch (an open PR), base the local branch on
        the REMOTE tip via a hard reset;
      * otherwise create the branch from an up-to-date ``origin/main``.
    """
    repo = gitlib.Repo(repo_dir)
    origin = repo.remotes.origin

    logger.info("Fetching origin")
    origin.fetch(prune=True)

    if _remote_branch_exists(repo, branch_name):
        remote_ref = origin.refs[branch_name]
        if branch_name in [h.name for h in repo.heads]:
            repo.heads[branch_name].checkout()
        else:
            repo.create_head(branch_name, remote_ref)
            repo.heads[branch_name].set_tracking_branch(remote_ref)
            repo.heads[branch_name].checkout()
        # Match the remote tip exactly so our commit is a clean child of it.
        repo.git.reset("--hard", remote_ref.name)
        logger.info("Based %s on remote tip %s", branch_name, remote_ref.name)
    else:
        repo.heads.main.checkout()
        repo.git.reset("--hard", "origin/main")
        if branch_name in [h.name for h in repo.heads]:
            repo.heads[branch_name].checkout()
        else:
            repo.create_head(branch_name).checkout()
        logger.info("Created %s from origin/main", branch_name)


def _push_branch(repo: gitlib.Repo, branch_name: str) -> None:
    """Push ``branch_name`` to origin, raising if the remote rejected it."""
    results = repo.remotes.origin.push(refspec=f"{branch_name}:{branch_name}")
    for info in results:
        if info.flags & _PUSH_ERROR_FLAGS:
            raise RuntimeError(f"Failed to push {branch_name}: {info.summary}")
    logger.info("Pushed branch %s to origin", branch_name)


def commit_and_pr(state: ServiceDeployState) -> dict[str, Any]:
    """Clone/sync repo, write manifests, commit, push, open PR."""
    settings = get_settings()
    workdir = Path(settings.repo_location)

    owner: str = state.get("_owner", "")  # type: ignore[typeddict-item]
    repo_name: str = state.get("_repo", "")  # type: ignore[typeddict-item]

    if not owner or not repo_name:
        return {"pr_url": "ERROR: _owner and _repo must be set in state to commit changes."}

    spec = state.get("spec", {})
    service_name = spec.get("name", "service")
    branch = f"ops-agent/deploy-{service_name}"
    manifests = state.get("manifests", {})

    try:
        repo_dir = _get_or_clone_repo(
            owner,
            repo_name,
            workdir,
            settings.github_base_url,
            settings.github_token,
        )

        _sync_and_branch(repo_dir, branch)

        deploy_dir = repo_dir / "apps" / service_name
        deploy_dir.mkdir(parents=True, exist_ok=True)
        for fname, content in manifests.items():
            (deploy_dir / fname).write_text(content, encoding="utf-8")

        repo = gitlib.Repo(repo_dir)
        repo.git.add(A=True)
        author = gitlib.Actor(settings.git_author_name, settings.git_author_email)
        issue_number = state.get("issue_number")
        commit_msg = f"feat: add {service_name} deployment manifests"
        if issue_number:
            commit_msg += f" #{issue_number}"
        repo.index.commit(
            commit_msg,
            author=author,
            committer=author,
        )
        _push_branch(repo, branch)
    except Exception as exc:
        # Re-raise so the graph does NOT checkpoint this as a completed run.
        # Swallowing the error into pr_url makes LangGraph mark the thread
        # "finished", which permanently caches the failure and blocks retries.
        # Raising leaves commit_and_pr as the pending node so a later run
        # resumes here (or use --fresh to start over).
        logger.error("Git operation failed: %s", exc, exc_info=True)
        raise

    existing_pr_index = state.get("pr_index")

    # Re-drive / steer turn: the PR is already open and we just pushed the
    # updated manifests to its branch. Don't open a second PR — acknowledge the
    # steering comment instead (which also advances the comment boundary so the
    # same comment can't re-trigger triage next tick).
    if existing_pr_index:
        client = GitHubClient()
        try:
            try:
                client.post_issue_comment(
                    owner, repo_name, existing_pr_index, _build_steer_ack(state)
                )
            except Exception as exc:
                logger.warning("could not post steer ack on PR #%s: %s", existing_pr_index, exc)
        finally:
            client.close()
        logger.info("Pushed update to existing PR #%s", existing_pr_index)
        return {"pr_url": state.get("pr_url"), "pr_index": existing_pr_index, "pr_branch": branch}

    # First run: open the PR and remember its identity for later turns.
    try:
        client = GitHubClient()
        try:
            pr = client.create_pr(
                owner=owner,
                repo=repo_name,
                title=f"feat: deploy {service_name}",
                body=_build_pr_body(state),
                head=branch,
                base="main",
            )
            pr_url = pr.get("html_url", str(pr))
            pr_index = pr.get("number")
            logger.info("Created PR: %s", pr_url)
        finally:
            client.close()
    except Exception as exc:
        logger.error("PR creation failed: %s", exc, exc_info=True)
        return {"pr_url": f"Branch pushed but PR creation failed: {exc}"}

    return {"pr_url": pr_url, "pr_index": pr_index, "pr_branch": branch}
